#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

export RUST_LOG="${RUST_LOG:-info}"
export FLIGHT_ADDR="${FLIGHT_ADDR:-0.0.0.0:50051}"
export METRICS_ENABLED="${METRICS_ENABLED:-true}"
export METRICS_ADDR="${METRICS_ADDR:-0.0.0.0:9090}"
export WORKER_ID="${WORKER_ID:-local-worker}"
export WORKER_FLIGHT_URI="${WORKER_FLIGHT_URI:-http://127.0.0.1:50051}"
export WORKER_DRAINING="${WORKER_DRAINING:-false}"
export WORKER_REQUIRE_STRUCTURED_TICKETS="${WORKER_REQUIRE_STRUCTURED_TICKETS:-false}"
export WORKER_HEARTBEAT_INTERVAL_MS="${WORKER_HEARTBEAT_INTERVAL_MS:-5000}"
export WORKER_REGISTRY_TTL_MS="${WORKER_REGISTRY_TTL_MS:-15000}"
export S3_ENDPOINT="${S3_ENDPOINT:-http://127.0.0.1:9000}"
export S3_BUCKET="${S3_BUCKET:-arrow-flight}"
export S3_REGION="${S3_REGION:-us-east-1}"
export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-minioadmin}"
export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-minioadmin}"
export AWS_ALLOW_HTTP="${AWS_ALLOW_HTTP:-true}"
export PARQUET_COMPRESSION="${PARQUET_COMPRESSION:-snappy}"
export PARQUET_DICTIONARY="${PARQUET_DICTIONARY:-false}"
export S3_MULTIPART_PART_SIZE="${S3_MULTIPART_PART_SIZE:-67108864}"
export S3_MULTIPART_MAX_CONCURRENCY="${S3_MULTIPART_MAX_CONCURRENCY:-16}"
export PUT_PARALLELISM="${PUT_PARALLELISM:-4}"
export PUT_QUEUE_DEPTH="${PUT_QUEUE_DEPTH:-2}"
export READ_MAX_ACTIVE_STREAMS="${READ_MAX_ACTIVE_STREAMS:-16}"
export READ_SLOT_WAIT_MS="${READ_SLOT_WAIT_MS:-30000}"
export FLIGHT_MAX_MESSAGE_SIZE="${FLIGHT_MAX_MESSAGE_SIZE:-268435456}"
export FLIGHT_DATA_CHUNK_SIZE="${FLIGHT_DATA_CHUNK_SIZE:-16777216}"

cargo run --release --bin flight-server
